version: '3.8'
services:
  app:
    build: .
    container_name: next-dental-lab-backend-case-service
    ports:
      - 8002:8002
    tty: true
    restart: unless-stopped
    stdin_open: true
    environment:
      - DATABASE_URL=postgresql://postgres:jignesh123@db:5432/nextdental
      - USER_SERVER_BACKEND=http://52.14.102.237:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:13
    container_name: postgres_db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jignesh123
      POSTGRES_DB: nextdental
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
