import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedShades() {
  const shadesData = [
    { shadeName: 'A1' },
    { shadeName: 'A2' },
    { shadeName: 'A3' },
    { shadeName: 'A3.5' },
    { shadeName: 'A4' },
    { shadeName: 'B1' },
    { shadeName: 'B2' },
    { shadeName: 'B3' },
    { shadeName: 'B4' },
    { shadeName: 'C1' },
    { shadeName: 'C2' },
    { shadeName: 'C3' },
    { shadeName: 'C4' },
    { shadeName: 'D2' },
    { shadeName: 'D3' },
    { shadeName: 'D4' },
    { shadeName: '1M1' },
    { shadeName: '3R1.5' },
    { shadeName: '2L1.5' },
    { shadeName: '2M1' },
    { shadeName: '2R1.5' },
    { shadeName: '1M2' },
    { shadeName: '3L1.5' },
    { shadeName: '3M1' },
    { shadeName: '3R2.5' },
    { shadeName: '1M3' },
    { shadeName: '2L2.5' },
    { shadeName: '2M2' },
    { shadeName: '2R2.5' },
    { shadeName: '3L2.5' },
    { shadeName: '3M2' },
    { shadeName: '3R3.5' },
    { shadeName: '4M1' },
    { shadeName: '4L1.5' },
    { shadeName: '4R1.5' },
    { shadeName: '5M1' },
    { shadeName: '5L1.5' },
    { shadeName: '5R1.5' },
    { shadeName: '5L2.5' },
    { shadeName: '5M2' },
    { shadeName: '5R2.5' },
    { shadeName: '4M2' },
    { shadeName: '4L2.5' },
    { shadeName: '4R2.5' },
    { shadeName: '0M1' },
    { shadeName: '0M2' },
    { shadeName: '0M3' },
    { shadeName: '1M1' },
    { shadeName: '2M1' },
    { shadeName: '3M1' },
    { shadeName: '4M1' },
    { shadeName: '5M1' },
    { shadeName: '1M2' },
    { shadeName: '2M2' },
    { shadeName: '3M2' },
    { shadeName: '4M2' },
    { shadeName: '5M2' },
    { shadeName: '2L1.5' },
    { shadeName: '3L1.5' },
    { shadeName: '4L1.5' },
    { shadeName: '5L1.5' },
    { shadeName: '2R1.5' },
    { shadeName: '3R1.5' },
    { shadeName: '4R1.5' },
    { shadeName: '5R1.5' },
    { shadeName: '2L2.5' },
    { shadeName: '3L2.5' },
    { shadeName: '4L2.5' },
    { shadeName: '5L2.5' },
    { shadeName: '2R2.5' },
    { shadeName: '3R2.5' },
    { shadeName: '4R2.5' },
    { shadeName: '5R2.5' },
    { shadeName: '100' },
    { shadeName: '200' },
    { shadeName: '300' },
    { shadeName: '400' },
    { shadeName: '500' },
    { shadeName: 'BL1' },
    { shadeName: 'BL2' },
    { shadeName: 'BL3' },
    { shadeName: 'BL4' },
    { shadeName: 'OM1' },
    { shadeName: 'OM2' },
    { shadeName: 'OM3' },
    { shadeName: '2M3' },
    { shadeName: '3M3' },
    { shadeName: '4M3' },
    { shadeName: '5M3' },
    { shadeName: 'Other' }
  ];

  try {
    await prisma.shades.createMany({
      data: shadesData,
      skipDuplicates: true
    });
  } catch (error) {
  } finally {
    await prisma.$disconnect();
  }
}

seedShades();
